openapi: 3.1.0
x-stoplight:
  id: a2o2rot3xm5pk
info:
  title: client-api
  version: '1.0'
  license:
    name: GPL 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'
  contact:
    name: Admin
    email: admin@wolkeneis.dev
    url: 'https://wolkeneis.dev/contact'
  termsOfService: 'https://wolkeneis.dev/privacy'
  description: The Public Moos Client API
  summary: Client API
servers:
  - url: 'https://moos.wolkeneis.dev/api/v1/client'
    description: Client Endpoint
paths: {}
components:
  schemas: {}
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          tokenUrl: 'https://moos.wolkeneis.dev/oauth2/token'
          refreshUrl: 'https://moos.wolkeneis.dev/oauth2/refresh'
          scopes:
            '*': ''
          authorizationUrl: 'https://moos.wolkeneis.dev/oauth2/authorize'
        implicit:
          authorizationUrl: 'https://moos.wolkeneis.dev/oauth2/authorize'
          scopes:
            '*': ''
          refreshUrl: 'https://moos.wolkeneis.dev/oauth2/refresh'
    bearer:
      type: http
      scheme: bearer
