openapi: 3.1.0
x-stoplight:
  id: mgmu7g11gm8zb
info:
  title: cookie-api
  version: "1.0"
  summary: Cookie API
  description: Endpoints for requesting and revoking Moos session cookies.
  contact:
    name: Admin
    url: "https://wolkeneis.dev/contact"
    email: admin@wolkeneis.dev
  termsOfService: "https://wolkeneis.dev/privacy"
  license:
    name: GPL 3.0
    url: "https://www.gnu.org/licenses/gpl-3.0.html"
servers:
  - url: "https://moos.wolkeneis.dev/cookie"
    description: Cookie Endpoint
paths:
  /request:
    post:
      summary: ""
      operationId: post-request
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "403":
          description: Forbidden
      description: Endpoint for requesting a session cookie
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
              required:
                - token
        description: ""
      parameters: []
  /revoke:
    delete:
      summary: ""
      operationId: delete-revoke
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
      parameters:
        - schema:
            type: string
          in: cookie
          name: session
          description: "The session cookie to revoke. "
          required: true
      description: Endpoint for revoking a session cookie
components:
  schemas: {}
  securitySchemes:
    CSRF-Token:
      name: CSRF Token
      type: apiKey
      in: header
      description: ""
security:
  - CSRF-Token: []
