openapi: 3.1.0
x-stoplight:
  id: ceneki1ll15ms
info:
  title: csrf-token-api
  version: '1.0'
  contact:
    name: Admin
    url: 'https://wolkeneis.dev/contact'
    email: admin@wolkeneis.dev
  termsOfService: 'https://wolkeneis.dev/privacy'
  license:
    name: GPL 3.0
    url: 'https://www.gnu.org/licenses/gpl-3.0.html'
  summary: CSRF Token API
  description: Endpoint for requesting a CSRF Token
servers:
  - url: 'https://moos.wolkeneis.dev/api/v1/csrf-token'
    description: CSRF Endpoint
paths:
  /request:
    post:
      summary: ''
      operationId: post-request
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _csrf:
                    type: string
                required:
                  - _csrf
      description: Endpoint for requesting the CSRF Token
  /try:
    post:
      summary: ''
      operationId: post-try
      responses:
        '204':
          description: No Content
        '403':
          description: Invalid csrf token
      security:
        - CSRF-Token: []
components:
  schemas: {}
  securitySchemes:
    CSRF-Token:
      name: CSRF Token
      type: apiKey
      in: header
