/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/profile": {
    /** Get your own Profile, if you are logged in with a session cookie */
    post: operations["fetch-profile"];
    /** Update your own Profile information, if you are logged in with a session cookie */
    patch: operations["patch-profile"];
  };
  "/csrf-token": {
    /** Endpoint for requesting the CSRF Token */
    get: operations["get-csrf-token"];
    /** Endpoint for testing the CSRF Token */
    post: operations["test-csrf-token"];
  };
  "/session": {
    /** Endpoint for requesting a session cookie */
    post: operations["request-session"];
    /** Endpoint for revoking a session cookie */
    delete: operations["revoke-session"];
  };
  "/client/profile": {
    /** Fetch profile associated with the bearer token. */
    post: operations["post-client-profile"];
  };
}

export interface components {
  schemas: {
    /** Profile */
    UserProfile: {
      uid: string;
      username: string;
      /** Format: uri */
      avatar: unknown;
      scopes: "*"[];
      private: boolean;
      providers?: components["schemas"]["ProviderProfile"][];
      clients: string[];
      /** Format: int64 */
      creationDate: number;
    };
    /** provider-profile */
    ProviderProfile: {
      /** @enum {string} */
      provider: "discord";
      providerId: string;
      username: string;
      /** Format: uri */
      avatar: unknown;
    };
    /** client */
    Client: {
      id: string;
      name: string;
      /** Format: uri */
      redirectUri: string;
      owner: string;
      trusted: boolean;
      /** Format: int64 */
      creationDate: number;
    };
  };
  requestBodies: {};
}

export interface operations {
  /** Get your own Profile, if you are logged in with a session cookie */
  "fetch-profile": {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserProfile"];
        };
      };
      /** Invalid csrf token */
      403: unknown;
      /** Internal Server Error */
      500: unknown;
    };
  };
  /** Update your own Profile information, if you are logged in with a session cookie */
  "patch-profile": {
    responses: {
      /** OK */
      200: unknown;
      /** Forbidden */
      403: unknown;
      /** Internal Server Error */
      500: unknown;
    };
    requestBody: {
      content: {
        "application/json": {
          private?: boolean;
        };
      };
    };
  };
  /** Endpoint for requesting the CSRF Token */
  "get-csrf-token": {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            _csrf: string;
          };
        };
      };
    };
  };
  /** Endpoint for testing the CSRF Token */
  "test-csrf-token": {
    responses: {
      /** No Content */
      204: never;
      /** Invalid csrf token */
      403: unknown;
    };
  };
  /** Endpoint for requesting a session cookie */
  "request-session": {
    responses: {
      /** No Content */
      204: never;
      /** Bad Request */
      400: unknown;
      /** Invalid csrf token */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": {
          token: string;
        };
      };
    };
  };
  /** Endpoint for revoking a session cookie */
  "revoke-session": {
    responses: {
      /** No Content */
      204: never;
      /** Invalid csrf token */
      403: unknown;
      /** Internal Server Error */
      500: unknown;
    };
  };
  /** Fetch profile associated with the bearer token. */
  "post-client-profile": {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserProfile"];
        };
      };
      /** Bad Request */
      400: unknown;
    };
  };
}

export interface external {}
