/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/profile/self": {
    post: operations["post-self"];
  };
  "/csrf-token": {
    /** Endpoint for requesting the CSRF Token */
    get: operations["get-csrf-token"];
    /** Endpoint for testing the CSRF Token */
    post: operations["post-csrf-token"];
  };
  "/session/request": {
    /** Endpoint for requesting a session cookie */
    post: operations["post-request"];
  };
  "/session/revoke": {
    /** Endpoint for revoking a session cookie */
    delete: operations["delete-revoke"];
  };
}

export interface components {
  schemas: {
    /** Profile */
    UserProfile: {
      uid: string;
      username: string;
      /** Format: uri */
      avatar: unknown;
      scopes: "*"[];
      private: boolean;
      providers?: components["schemas"]["ProviderProfile"][];
      clients: string[];
      /** Format: int64 */
      creationDate: number;
    };
    /** provider-profile */
    ProviderProfile: {
      /** @enum {string} */
      provider: "discord";
      providerId: string;
      username: string;
      /** Format: uri */
      avatar: unknown;
    };
    /** client */
    Client: {
      id: string;
      name: string;
      /** Format: uri */
      redirectUri: string;
      owner: string;
      trusted: boolean;
      /** Format: int64 */
      creationDate: number;
    };
  };
}

export interface operations {
  "post-self": {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": components["schemas"]["UserProfile"];
        };
      };
      /** Invalid csrf token */
      403: unknown;
    };
  };
  /** Endpoint for requesting the CSRF Token */
  "get-csrf-token": {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            _csrf: string;
          };
        };
      };
    };
  };
  /** Endpoint for testing the CSRF Token */
  "post-csrf-token": {
    responses: {
      /** No Content */
      204: never;
      /** Invalid csrf token */
      403: unknown;
    };
  };
  /** Endpoint for requesting a session cookie */
  "post-request": {
    parameters: {};
    responses: {
      /** No Content */
      204: never;
      /** Bad Request */
      400: unknown;
      /** Invalid csrf token */
      403: unknown;
    };
    requestBody: {
      content: {
        "application/json": {
          token: string;
        };
      };
    };
  };
  /** Endpoint for revoking a session cookie */
  "delete-revoke": {
    parameters: {};
    responses: {
      /** No Content */
      204: never;
      /** Invalid csrf token */
      403: unknown;
      /** Internal Server Error */
      500: unknown;
    };
  };
}

export interface external {}
